AlTER TABLE FactTable ADD CONSTRAINT 
FK_BeatID FOREIGN KEY (Beat_ID)REFERENCES DimBeat(ID);
AlTER TABLE FactTable ADD CONSTRAINT 
FK_CrimeID FOREIGN KEY (Crime_ID)REFERENCES DimCrime(ID);
AlTER TABLE FactTable ADD CONSTRAINT 
FK_LocationID FOREIGN KEY (Location_ID)REFERENCES DimLocation(ID);
AlTER TABLE FactTable ADD CONSTRAINT 
FK_TimeID FOREIGN KEY (Time_ID)REFERENCES DimTime(ID);
AlTER TABLE FactTable ADD CONSTRAINT 
FK_TypeID FOREIGN KEY (Type_of_crime_location_ID)REFERENCES DimType(ID);
Go